import { Dimensions, Platform, PixelRatio } from 'react-native'
import NormalizeSize from '../Themes/NormalizeSize';
const { width, height } = Dimensions.get('window')

const metrics = {

    banner_height: (NormalizeSize.getWPercent('100%') * 4 / 7) + (Platform.OS === 'android' ? NormalizeSize.getH(30) : NormalizeSize.getH(20)),
    development_banner_height: (NormalizeSize.getWPercent('60%') * 4 / 7) + (Platform.OS === 'android' ? NormalizeSize.getH(30) : NormalizeSize.getH(20)),

    introtitle: NormalizeSize.getFontSize(25),
    introDesc:NormalizeSize.getFontSize(13.5),
    introNextTitle :NormalizeSize.getFontSize(16),
    loginText :NormalizeSize.getFontSize(22),
    loginTextDesc :NormalizeSize.getFontSize(14),
    text_9: NormalizeSize.getFontSize(9),
    text_10: NormalizeSize.getFontSize(10),
    text_10_5: NormalizeSize.getFontSize(10.5),
    text_11: NormalizeSize.getFontSize(11),
    text_12: NormalizeSize.getFontSize(12),
    text_13: NormalizeSize.getFontSize(13),
    text_14: NormalizeSize.getFontSize(14),
    text_15: NormalizeSize.getFontSize(15),
    text_16: NormalizeSize.getFontSize(16),
    text_17: NormalizeSize.getFontSize(17),
    text_18: NormalizeSize.getFontSize(18),
    text_19: NormalizeSize.getFontSize(19),
    text_20: NormalizeSize.getFontSize(20),
    text_21: NormalizeSize.getFontSize(21),
    text_22: NormalizeSize.getFontSize(22),
    text_23: NormalizeSize.getFontSize(23),
    text_24: NormalizeSize.getFontSize(24),
    text_25: NormalizeSize.getFontSize(25),
    text_26: NormalizeSize.getFontSize(26),
    font_weight_button: '500',
    width: width,
    height: height,
    marginHorizontal: 10,
    marginVertical: 10,
    section: 25,
    baseMargin: 10,
    doubleBaseMargin: 20,
    smallMargin: 5,
    doubleSection: 50,
    horizontalLineHeight: 1,
    screenWidth: width < height ? width : height,
    screenHeight: width < height ? height : width,
    navBarHeight: (Platform.OS === 'ios') ? 64 : 54,
    buttonRadius: 5,
    borderWidth: 2,
    dimen_5: NormalizeSize.getH(5),
    dimen_6: NormalizeSize.getH(6),
    dimen_7: NormalizeSize.getH(7),
    dimen_1: NormalizeSize.getH(1),
    dimen_tiny: NormalizeSize.getH(0.5),
    dimen_2: NormalizeSize.getH(2),
    dimen_3: NormalizeSize.getH(3),
    dimen_4: NormalizeSize.getH(4),
    dimen_8: NormalizeSize.getH(8),
    dimen_9: NormalizeSize.getH(9),
    dimen_10: NormalizeSize.getH(10),
    dimen_12: NormalizeSize.getH(12),
    dimen_14: NormalizeSize.getH(14),
    dimen_15: NormalizeSize.getH(15),
    dimen_16: NormalizeSize.getH(16),
    dimen_18: NormalizeSize.getH(18),
    dimen_20: NormalizeSize.getH(20),
    dimen_22: NormalizeSize.getH(22),
    dimen_24: NormalizeSize.getH(24),
    dimen_25: NormalizeSize.getH(25),
    dimen_27: NormalizeSize.getH(27),
    dimen_28: NormalizeSize.getH(28),
    dimen_30: NormalizeSize.getH(30),
    dimen_35: NormalizeSize.getH(35),
    dimen_36: NormalizeSize.getH(36),
    dimen_40: NormalizeSize.getH(40),
    dimen_42: NormalizeSize.getH(42),
    dimen_44: NormalizeSize.getH(44),
    dimen_45: NormalizeSize.getH(45),
    dimen_48: NormalizeSize.getH(48),
    dimen_50: NormalizeSize.getH(50),
    dimen_55: NormalizeSize.getH(55),
    dimen_56: NormalizeSize.getH(56),
    dimen_60: NormalizeSize.getH(60),
    dimen_64: NormalizeSize.getH(64),
    dimen_65: NormalizeSize.getH(65),
    dimen_70: NormalizeSize.getH(70),
    dimen_72: NormalizeSize.getH(72),
    dimen_75: NormalizeSize.getH(75),
    dimen_80: NormalizeSize.getH(80),
    dimen_90: NormalizeSize.getH(90),
    dimen_92: NormalizeSize.getH(92),
    dimen_96: NormalizeSize.getH(96),
    dimen_100: NormalizeSize.getH(100),
    dimen_120: NormalizeSize.getH(120),
    dimen_130: NormalizeSize.getH(130),
    dimen_140: NormalizeSize.getH(140),
    dimen_150: NormalizeSize.getH(150),
    dimen_160: NormalizeSize.getH(160),
    dimen_180: NormalizeSize.getH(180),
    dimen_190: NormalizeSize.getH(190),
    dimen_200: NormalizeSize.getH(200),
    dimen_220: NormalizeSize.getH(220),
    dimen_230: NormalizeSize.getH(230),
    dimen_240: NormalizeSize.getH(240),
    dimen_250: NormalizeSize.getH(250),
    dimen_300: NormalizeSize.getH(300),
    getH: (size) => NormalizeSize.getH(size),
    getHPercent: (percent) => NormalizeSize.getHPercent(percent),
    getW: (size) => NormalizeSize.getW(size),
    getWPercent: (percent) => NormalizeSize.getWPercent(percent),
    getFontSize: (size) => NormalizeSize.getFontSize(size),

    
}

export default metrics